-- MySQL Script generated by MySQL Workbench
-- 11/21/17 19:27:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Flightdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Flightdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Flightdb` ;
USE `Flightdb` ;

-- -----------------------------------------------------
-- Table `Flightdb`.`Seat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Flightdb`.`Seat` (
  `seatNumber` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`seatNumber`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flightdb`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Flightdb`.`Ticket` (
  `ticketId` INT NOT NULL,
  `date` DATE NOT NULL,
  `flightType` VARCHAR(10) NOT NULL,
  `price` DECIMAL(13,4) NOT NULL,
  `Seat_seatNumber` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ticketId`),
  INDEX `fk_Ticket_Seat1_idx` (`Seat_seatNumber` ASC),
  CONSTRAINT `fk_Ticket_Seat1`
    FOREIGN KEY (`Seat_seatNumber`)
    REFERENCES `Flightdb`.`Seat` (`seatNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flightdb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Flightdb`.`Customer` (
  `passportNo` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `phoneNo` VARCHAR(15) NOT NULL,
  `cardNo` VARCHAR(20) NOT NULL,
  `Ticket_ticketId` INT NOT NULL,
  PRIMARY KEY (`passportNo`),
  INDEX `fk_Customer_Ticket_idx` (`Ticket_ticketId` ASC),
  CONSTRAINT `fk_Customer_Ticket`
    FOREIGN KEY (`Ticket_ticketId`)
    REFERENCES `Flightdb`.`Ticket` (`ticketId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Flightdb`.`Flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Flightdb`.`Flight` (
  `flightId` INT NOT NULL,
  `numberOfSeats` INT NOT NULL,
  `flightType` VARCHAR(15) NOT NULL,
  `destination` VARCHAR(25) NOT NULL,
  `depDateTime` DATETIME NULL,
  `arrDateTime` DATETIME NULL,
  `maxBaggage` INT NOT NULL,
  `Seat_seatNumber` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`flightId`),
  INDEX `fk_Flight_Seat1_idx` (`Seat_seatNumber` ASC),
  CONSTRAINT `fk_Flight_Seat1`
    FOREIGN KEY (`Seat_seatNumber`)
    REFERENCES `Flightdb`.`Seat` (`seatNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
